name: Type Checking

on: [push, pull_request]

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install --with dev

    - name: Install mypy 1.7.1
      run: poetry add mypy==1.7.1 --dev

    - name: Run mypy
      run: poetry run mypy . --config-file mypy.ini
